from enum import Enum


class EnvrionmentVariable(Enum):
    TWITTER_ACCESS_TOKEN = 'TWITTER_ACCESS_TOKEN'
    TWITTER_ACCESS_TOKEN_SECRET = 'TWITTER_ACCESS_TOKEN_SECRET'
    TWITTER_API_KEY = 'TWITTER_API_KEY'
    TWITTER_API_SECRET = 'TWITTER_API_SECRET'
    TWITTER_CLIENT_ACCESS_TOKEN = 'TWITTER_CLIENT_ACCESS_TOKEN'
    TWITTER_CLIENT_ACCESS_TOKEN_SECRET = 'TWITTER_CLIENT_ACCESS_TOKEN_SECRET'
